# Generated by Django 4.0.5 on 2022-06-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passingYards', models.FloatField()),
                ('rushingYards', models.FloatField()),
                ('passingYardsAllowedDefense', models.FloatField()),
                ('rushingYardsAllowedDefense', models.FloatField()),
                ('turnoversCreated', models.FloatField()),
                ('thirdDownsConverted', models.FloatField()),
                ('sacks', models.FloatField()),
            ],
        ),
    ]
